version: '3'
services:
    server:
        build:
            context: .
        container_name: socket-server
        restart: always
        volumes:
            - /usr/src/server/node_modules
            - ./:/usr/src/server
        ports:
            - "8080:8080"
        command:
            "npm run start"
    nginx:
        image: nginx:1.13
        container_name: socket-server-nginx
        ports: 
            - "80:80"
        volumes: 
            - ./nginx:/etc/nginx/conf.d
        depends_on: 
            - server
        logging: 
            driver: json-file