version: '3'
services:
    server:
        build:
            context: .
        container_name: socket-server
        restart: always
        volumes:
            - /usr/src/server/node_modules
            - ./:/usr/src/server
        ports:
            - "8080:8080"
        command:
            "npm run start"
        networks:
            - app-network

    nginx:
        image: nginx:1.13
        container_name: socket-server-nginx
        restart: unless-stopped
        ports: 
            - "80:80"
        volumes: 
            - web-root:/var/www/html
            - ./nginx:/etc/nginx/conf.d
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
        depends_on: 
            - server
        networks:
            - app-network
        logging: 
            driver: json-file

    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - web-root:/var/www/html
        depends_on:
            - server
        command: certonly --webroot --webroot-path=/var/www/html --email dasolari@uc.cl --agree-tos --no-eff-email --staging -d socketsadmin.tk  -d www.socketsadmin.tk

volumes:
    certbot-etc:
    certbot-var:
    web-root:
        driver: local
        driver_opts:
            type: none
            device: /
            o: bind

networks:
    app-network:
        driver: bridge